import os
TELEGRAM_BOT_TOKEN=os.getenv('TELEGRAM_BOT_TOKEN')
AMAZON_AFFILIATE_TAG=os.getenv('AMAZON_AFFILIATE_TAG')
DB_HOST=os.getenv('DB_HOST')
DB_USER=os.getenv('DB_USER')
DB_PASS=os.getenv('DB_PASS')
DB_NAME=os.getenv('DB_NAME')