[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:cron]
command=/usr/sbin/cron -f
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/cron.log
stderr_logfile=/var/log/supervisor/cron_err.log

[program:telegram-bot]
command=python main.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/bot.log
stderr_logfile=/var/log/supervisor/bot_err.log

[program:flask-app]
command=python api.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/flask.log
stderr_logfile=/var/log/supervisor/flask_err.log

[program:session_bot]
command=/app/start_session_bot.sh
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/session.log
stderr_logfile=/var/log/supervisor/session_err.log
